version: "3.8"


services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "3001:3000" # наружу 3001, внутри 3000
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "5173" # внутренний порт для Docker сети
    ports:
      - "5173:5173" # проброс наружу для Vite
    tty: true
    stdin_open: true
    environment:
      - PORT=5173 # если Vite читает порт из env

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./backend/data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./information.bautex.pro-fullchain.pem:/etc/ssl/certs/information.bautex.pro-fullchain.pem:ro
      - ./information.bautex.pro-key.pem:/etc/ssl/private/information.bautex.pro-key.pem:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
