version: "3.8"


services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "3001:3000" # наружу 3001, внутри 3000
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "5173" # внутренний порт для Docker сети
    ports:
      - "5173:5173" # проброс наружу для Vite
    tty: true
    stdin_open: true
    environment:
      - PORT=5173 # если Vite читает порт из env

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # пароль для root
      MYSQL_DATABASE: mydb                # создаст базу по умолчанию
      MYSQL_USER: user                    # дополнительный пользователь
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"        # проброс порта на локальную машину
    volumes:
      - ./backend/data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./framy.ai.srt:/framy.ai.srt
      - ./framy.ai.key:/framy.ai.key
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
